{% set version = "4.2.2" %}
{% set openjdk_version = "11.0.*" %}

package:
  name: denoptim
  version: {{ version }}

source:
  url: https://github.com/denoptim-project/DENOPTIM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 634ab9df4365e9c98e6de5716f8bb3e13d0457a9312382db8429061869d6efc6

build:
  number: 0

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - python
    - py4j

test:
  commands:
    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only AND OTHER
  license_file:
    - COPYING
    - licenses/THIRD-PARTY.txt
    - licenses/dependencies/
  summary: Package for de novo design and virtual screening of functional molecules of any kind.
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
