{% set version = "4.3.0" %}
{% set openjdk_version = "11.0.*" %}

package:
  name: denoptim
  version: {{ version }}

source:
  url: https://github.com/denoptim-project/DENOPTIM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 056a2e1c00290991c07c4d9f39280a3d78a330e1ddb82415648518befde9e19b

build:
  number: 0

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - python
    - py4j

test:
  commands:
    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only AND OTHER
  license_file:
    - COPYING
    - licenses/THIRD-PARTY.txt
    - licenses/dependencies/
  summary: Package for de novo design and virtual screening of functional molecules of any kind.
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
