{% set version = "4.6.7" %}
{% set openjdk_version = "17.*" %}

package:
  name: denoptim
  version: {{ version }}

source:
  url: https://github.com/denoptim-project/DENOPTIM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6daf51a74571047ed8c65a9148f31b666742cc3ec8e1c240b3cd8ce8f07c21c3

build:
  number: 0

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - python
    - py4j

test:
  commands:
    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only AND OTHER
  license_file:
    - COPYING
    - licenses/THIRD-PARTY.txt
    - licenses/license_files/
  summary: Package for de novo design and virtual screening of functional molecules of any kind.
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
