{% set version = "4.6.0" %}
{% set openjdk_version = "17.*" %}

package:
  name: denoptim
  version: {{ version }}

source:
  url: https://github.com/denoptim-project/DENOPTIM/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 81d3cfa1cae1e9075623dc6e4ec0523abbcaad5dc2d4afbf785323812f67f1dd

build:
  number: 0

requirements:
  build:
    - openjdk =={{ openjdk_version }}
    - maven
  run:
    - openjdk =={{ openjdk_version }}
    - python
    - py4j

test:
  commands:
    - denoptim -v

about:
  home: https://github.com/denoptim-project/DENOPTIM
  license: AGPL-3.0-only AND OTHER
  license_file:
    - COPYING
    - licenses/THIRD-PARTY.txt
    - licenses/license_files/
  summary: Package for de novo design and virtual screening of functional molecules of any kind.
  description: Package for de novo design and virtual screening of functional molecules of any kind.
  dev_url: https://github.com/denoptim-project/DENOPTIM
  doc_url: https://github.com/denoptim-project/DENOPTIM

extra:
  recipe-maintainers:
    - marco-foscato
